package com.bloodlink.forms;
import javax.swing.JOptionPane;
import com.bloodlink.utils.UserSession;  // ← ← ← Ito ang gagamitin!

public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
public LoginForm() {
    initComponents();
    
    // ✅ Optional: Redirect if already logged in
    if (UserSession.isLoggedIn && !UserSession.currentUser.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "ℹ️ You are already logged in!", 
            "Session Active", JOptionPane.INFORMATION_MESSAGE);
        
        DashboardForm dashboard = new DashboardForm();
        dashboard.loadUserData(UserSession.currentUser, UserSession.currentRole);
        dashboard.setVisible(true);
        this.dispose();
        return;
    }
}

 
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glassPanel1 = new customcontrols.GlassPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new CustomComponents.RoundedButton();
        logoLabel3 = new customcontrols.LogoLabel();
        txtPassword = new CustomComponents.PasswordFieldWithIcon();
        logoLabel2 = new customcontrols.LogoLabel();
        logoLabel1 = new customcontrols.LogoLabel();
        txtUsername = new CustomComponents.TextboxWithIcon();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        logoLabel4 = new customcontrols.LogoLabel();
        modernLabel1 = new customcontrols.ModernLabel();

        setTitle("BloodLink - Login");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        glassPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        glassPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 60, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        glassPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, -1));

        btnLogin.setText("Login ");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        glassPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 260, 40));

        logoLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N
        logoLabel3.setText("logoLabel3");
        glassPanel1.add(logoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 306, 40, 50));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        glassPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, -1));

        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        logoLabel2.setText("logoLabel2");
        glassPanel1.add(logoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 40, 70));

        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bloodlink_logo.png"))); // NOI18N
        logoLabel1.setText("logoLabel1");
        glassPanel1.add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 260, 240));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("Enter your ID");
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        glassPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 260, -1));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        glassPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel3.setText("Password");
        glassPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, -1));

        getContentPane().add(glassPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 430, 550));

        logoLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backdropicon.png"))); // NOI18N
        logoLabel4.setText("logoLabel4");
        getContentPane().add(logoLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-570, 100, 1250, 800));

        modernLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2026-05-06 232929.png"))); // NOI18N
        getContentPane().add(modernLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 1. Kunin ang input
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword());
    
    // 2. Basic Validation
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "⚠️ Please enter both username and password!", 
            "Input Required", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 3. Database Validation
    try {
        java.sql.Connection con = com.bloodlink.db.DBConnection.connect();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "❌ Cannot connect to database!", "Connection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, password); // ️ Plain text muna Hash later if needed.
        
        java.sql.ResultSet rs = pst.executeQuery();
        
if (rs.next()) {
    String fullName = rs.getString("full_name");
    String role = rs.getString("role");
    
    // ✅ SAVE SA UserSession
    UserSession.currentUser = fullName;
    UserSession.currentRole = role;
    UserSession.isLoggedIn = true;  // ← ← ← DAGDAGAN MO ITO!
    
    JOptionPane.showMessageDialog(this, 
        "✅ Login Successful!\nWelcome, " + fullName + " (" + role + ")", 
        "Success", JOptionPane.INFORMATION_MESSAGE);
    
    DashboardForm dashboard = new DashboardForm();
    dashboard.loadUserData(fullName, role);
    dashboard.setVisible(true);
    this.dispose();
    
} else {


            // ❌ LOGIN FAILED
            JOptionPane.showMessageDialog(this, 
                "🚫 Invalid username or password!", 
                "Login Failed", JOptionPane.ERROR_MESSAGE);
            
            // Clear password field for security
            txtPassword.setText("");
            txtUsername.requestFocus();
        }
        
        // 4. Clean up resources
        rs.close();
        pst.close();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "❌ System Error: " + e.getMessage(), 
            "Exception", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    if (jCheckBox1.isSelected()) {
        txtPassword.setEchoChar((char) 0); // Ipakita ang password
    } else {
        txtPassword.setEchoChar('•');      // Itago ulit
    }                            
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomComponents.RoundedButton btnLogin;
    private customcontrols.GlassPanel glassPanel1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private customcontrols.LogoLabel logoLabel1;
    private customcontrols.LogoLabel logoLabel2;
    private customcontrols.LogoLabel logoLabel3;
    private customcontrols.LogoLabel logoLabel4;
    private customcontrols.ModernLabel modernLabel1;
    private CustomComponents.PasswordFieldWithIcon txtPassword;
    private CustomComponents.TextboxWithIcon txtUsername;
    // End of variables declaration//GEN-END:variables
}
